//! Fleet-wide audit aggregation.
//!
//! The `jankurai fleet` command runs the existing full audit engine across a
//! list of repositories and emits a consolidated matrix that the JMCP universe
//! dashboard consumes. It composes the audit engine (it does not reimplement any
//! scoring logic); each repo is scored with `run_audit_with_options` and the
//! relevant report fields are projected into a stable matrix row.

use crate::audit::{run_audit_with_options, AuditOptions};
use crate::model::{Finding, Report, AUDITOR_VERSION};
use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::UNIX_EPOCH;

/// Stable note emitted in place of a wall-clock timestamp so the matrix is
/// reproducible for dashboard diffing and golden tests.
const GENERATED_AT_NOTE: &str =
    "Generated by jankurai fleet; per-repo audits are deterministic and carry their own timestamps.";

/// Maximum number of findings projected into each matrix row.
const TOP_FINDINGS_LIMIT: usize = 5;

/// Maximum number of tool-adoption opportunities projected into each matrix row.
const TOP_TOOL_OPPORTUNITIES_LIMIT: usize = 5;

/// Arguments for the fleet command.
#[derive(Debug, Clone)]
pub struct FleetArgs {
    /// Repo paths supplied positionally. When empty, the fleet list is read
    /// from `~/.jankurai/fleet.toml` if present.
    pub repos: Vec<PathBuf>,
    /// Optional output file; when absent the matrix is written to stdout.
    pub out: Option<String>,
    /// Output format: `json` (default) or `md`.
    pub format: String,
    /// When set, exit nonzero if any repo scores below this threshold.
    pub fail_under: Option<i32>,
    /// `full` (default; live audit per repo) or `cached` (read each repo's last
    /// `.jankurai/repo-score.json` — seconds, not minutes — flagged fresh/cached/stale).
    pub mode: String,
    /// In `full` mode, persist each repo's score to `.jankurai/repo-score.json` so a later
    /// `--mode cached` run has inputs. Default off to keep fleet read-only across the fleet.
    pub write_cache: bool,
}

/// One row of the consolidated fleet matrix, one per audited repo.
#[derive(Debug, Clone, Serialize)]
pub struct FleetRow {
    pub name: String,
    pub path: String,
    pub score: i32,
    pub raw: i32,
    pub caps: Vec<String>,
    pub hard_findings: usize,
    pub hl_level: String,
    pub top_findings: Vec<String>,
    pub top_tool_opportunities: Vec<String>,
    // ── v2 deterministic repo-state additions (the JMCP universe-dashboard data) ──
    // Appended (never inserted) so existing JSON key order stays stable. All
    // wall-clock fields are raw epoch seconds, never relative/formatted strings,
    // so the matrix stays reproducible for golden tests.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub head_sha: Option<String>,
    pub dirty_files: usize,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_commit_epoch: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_binary_epoch: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_tests_epoch: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    pub ci_configured: bool,
    /// `fresh` (live audit this run) | `cached` (reused, HEAD/ruleset unchanged) |
    /// `stale` (cached score, but HEAD moved / worktree dirty / auditor bumped). Always
    /// emitted so the dashboard never renders a stale score as current.
    pub score_freshness: String,
}

/// Deterministic repo identity/state shared by full and cached rows.
struct RepoMeta {
    version: Option<String>,
    branch: Option<String>,
    head_sha: Option<String>,
    dirty_files: usize,
    last_commit_epoch: Option<i64>,
    last_binary_epoch: Option<i64>,
    last_tests_epoch: Option<i64>,
    host: Option<String>,
    ci_configured: bool,
}

/// The subset of a persisted `.jankurai/repo-score.json` the fleet reuses in cached mode.
/// `Report` is serialize-only, so this is a tolerant deserialize shim (unknown fields ignored).
#[derive(Deserialize)]
struct CachedScore {
    score: i32,
    #[serde(default)]
    raw_score: i32,
    #[serde(default)]
    caps_applied: Vec<String>,
    #[serde(default)]
    observed_conformance_level: String,
    #[serde(default)]
    auditor_version: String,
    #[serde(default)]
    decision: Option<CachedDecision>,
    #[serde(default)]
    git: Option<CachedGit>,
}

#[derive(Deserialize)]
struct CachedDecision {
    #[serde(default)]
    hard_findings: usize,
}

#[derive(Deserialize)]
struct CachedGit {
    #[serde(default)]
    head: Option<String>,
}

/// Aggregate totals across the fleet, mirroring the census summary style used
/// by the public-repo-scores aggregation.
#[derive(Debug, Clone, Serialize)]
pub struct FleetTotals {
    pub repo_count: usize,
    pub audited: usize,
    pub failed: usize,
    pub min_score: Option<i32>,
    pub max_score: Option<i32>,
    pub average_score: Option<f64>,
    pub total_hard_findings: usize,
    pub below_threshold: usize,
}

/// A repo that could not be audited, recorded so callers see partial failures.
#[derive(Debug, Clone, Serialize)]
pub struct FleetError {
    pub path: String,
    pub error: String,
}

/// The full consolidated matrix: the data contract consumed by the dashboard.
#[derive(Debug, Clone, Serialize)]
pub struct FleetMatrix {
    pub generated_at_note: String,
    pub repos: Vec<FleetRow>,
    pub totals: FleetTotals,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub errors: Vec<FleetError>,
}

/// Entry point for `jankurai fleet`.
pub fn run(args: FleetArgs) -> Result<()> {
    let repos = resolve_repos(&args.repos)?;
    if repos.is_empty() {
        bail!("no repos to audit; pass repo paths or populate ~/.jankurai/fleet.toml");
    }
    let cached_mode = match args.mode.as_str() {
        "cached" => true,
        "full" | "" => false,
        other => bail!("unknown mode '{other}'; expected 'full' or 'cached'"),
    };

    let mut rows = Vec::new();
    let mut errors = Vec::new();
    for repo in &repos {
        if !repo.exists() {
            // A missing path is a fatal configuration error: surface it directly.
            bail!("repo path does not exist: {}", repo.display());
        }
        if cached_mode {
            match cached_row(repo) {
                Some(row) => rows.push(row),
                None => errors.push(FleetError {
                    path: display_path(repo),
                    error: "no cached score (.jankurai/repo-score.json); run a full audit first"
                        .to_string(),
                }),
            }
        } else {
            match audit_repo(repo) {
                Ok(report) => {
                    if args.write_cache {
                        // Best-effort: a cache-write failure must not fail the fleet run.
                        let _ = write_score_cache(repo, &report);
                    }
                    rows.push(build_row(repo, &report));
                }
                Err(err) => errors.push(FleetError {
                    path: display_path(repo),
                    error: err.to_string(),
                }),
            }
        }
    }

    let matrix = build_matrix(rows, errors, args.fail_under);
    let rendered = match args.format.as_str() {
        "md" => render_markdown(&matrix),
        "json" => serde_json::to_string_pretty(&matrix)?,
        other => bail!("unknown format '{other}'; expected 'json' or 'md'"),
    };

    emit(&args.out, &rendered)?;

    if let Some(threshold) = args.fail_under {
        if matrix.totals.below_threshold > 0 {
            bail!(
                "{} repo(s) scored below the fail-under threshold of {}",
                matrix.totals.below_threshold,
                threshold
            );
        }
    }

    Ok(())
}

/// Resolve the fleet list: explicit positional repos take precedence, otherwise
/// fall back to `~/.jankurai/fleet.toml` when present.
fn resolve_repos(explicit: &[PathBuf]) -> Result<Vec<PathBuf>> {
    if !explicit.is_empty() {
        return Ok(explicit.to_vec());
    }
    match fleet_config_path() {
        Some(path) if path.exists() => read_fleet_config(&path),
        _ => Ok(Vec::new()),
    }
}

fn fleet_config_path() -> Option<PathBuf> {
    std::env::var_os("HOME").map(|home| PathBuf::from(home).join(".jankurai/fleet.toml"))
}

/// Read the `repos` array from `~/.jankurai/fleet.toml`.
fn read_fleet_config(path: &Path) -> Result<Vec<PathBuf>> {
    let text = std::fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    parse_fleet_config(&text)
}

/// Parse a fleet config body. Expected shape: `repos = ["/a", "/b"]`.
fn parse_fleet_config(text: &str) -> Result<Vec<PathBuf>> {
    let value: toml::Value = toml::from_str(text).with_context(|| "parse fleet config as TOML")?;
    let repos = value
        .get("repos")
        .and_then(|v| v.as_array())
        .map(|items| {
            items
                .iter()
                .filter_map(|item| item.as_str())
                .map(PathBuf::from)
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();
    Ok(repos)
}

/// Run the existing full audit engine over a single repo.
fn audit_repo(repo: &Path) -> Result<Report> {
    run_audit_with_options(repo, &[], AuditOptions::default())
        .with_context(|| format!("audit {}", repo.display()))
}

/// Project a `Report` into a matrix row. All scoring lives in the audit engine;
/// this only selects and shapes existing report fields.
fn build_row(repo: &Path, report: &Report) -> FleetRow {
    let hard_findings = report
        .decision
        .as_ref()
        .map(|d| d.hard_findings)
        .unwrap_or_else(|| {
            report
                .findings
                .iter()
                .filter(|f| f.hardness == "hard")
                .count()
        });

    let meta = repo_metadata(repo);
    FleetRow {
        name: repo_name(repo),
        path: display_path(repo),
        score: report.score,
        raw: report.raw_score,
        caps: report.caps_applied.clone(),
        hard_findings,
        hl_level: report.observed_conformance_level.clone(),
        top_findings: top_findings(&report.findings),
        top_tool_opportunities: top_tool_opportunities(report),
        version: meta.version,
        branch: meta.branch,
        head_sha: meta.head_sha,
        dirty_files: meta.dirty_files,
        last_commit_epoch: meta.last_commit_epoch,
        last_binary_epoch: meta.last_binary_epoch,
        last_tests_epoch: meta.last_tests_epoch,
        host: meta.host,
        ci_configured: meta.ci_configured,
        score_freshness: "fresh".to_string(),
    }
}

/// Project a repo's last persisted score into a cached/stale row (cached mode).
/// Returns `None` only when no cached score file exists at all.
fn cached_row(repo: &Path) -> Option<FleetRow> {
    let path = crate::local_state::preferred_repo_path(
        repo,
        crate::local_state::SCORE_JSON,
        Some(crate::local_state::LEGACY_SCORE_JSON),
    );
    let text = std::fs::read_to_string(&path).ok()?;
    let cached: CachedScore = serde_json::from_str(&text).ok()?;
    let meta = repo_metadata(repo);
    let score_freshness = cached_freshness(&cached, &meta);
    let hard_findings = cached
        .decision
        .as_ref()
        .map(|d| d.hard_findings)
        .unwrap_or(0);
    Some(FleetRow {
        name: repo_name(repo),
        path: display_path(repo),
        score: cached.score,
        raw: cached.raw_score,
        caps: cached.caps_applied,
        hard_findings,
        hl_level: cached.observed_conformance_level,
        // Cached mode is the fast, lightweight view; per-finding detail comes from a full run.
        top_findings: Vec::new(),
        top_tool_opportunities: Vec::new(),
        version: meta.version,
        branch: meta.branch,
        head_sha: meta.head_sha,
        dirty_files: meta.dirty_files,
        last_commit_epoch: meta.last_commit_epoch,
        last_binary_epoch: meta.last_binary_epoch,
        last_tests_epoch: meta.last_tests_epoch,
        host: meta.host,
        ci_configured: meta.ci_configured,
        score_freshness,
    })
}

/// A cached score is `cached` (safe to show as current) only when it reflects the current
/// committed state AND the current ruleset: HEAD unchanged, worktree clean, auditor version
/// matched. Conservative — any doubt yields `stale`, never a silently-current stale score.
fn cached_freshness(cached: &CachedScore, meta: &RepoMeta) -> String {
    let cached_head = cached.git.as_ref().and_then(|g| g.head.as_deref());
    let head_match =
        matches!((cached_head, meta.head_sha.as_deref()), (Some(c), Some(n)) if c == n);
    let clean = meta.dirty_files == 0;
    let auditor_match = cached.auditor_version == AUDITOR_VERSION;
    if head_match && clean && auditor_match {
        "cached".to_string()
    } else {
        "stale".to_string()
    }
}

/// Sort findings hard-first then by severity rank, returning short summaries.
fn top_findings(findings: &[Finding]) -> Vec<String> {
    let mut sorted: Vec<&Finding> = findings.iter().collect();
    sorted.sort_by(|a, b| {
        let a_hard = u8::from(a.hardness != "hard");
        let b_hard = u8::from(b.hardness != "hard");
        a_hard
            .cmp(&b_hard)
            .then_with(|| severity_rank(&a.severity).cmp(&severity_rank(&b.severity)))
            .then_with(|| a.check_id.cmp(&b.check_id))
    });
    sorted
        .into_iter()
        .take(TOP_FINDINGS_LIMIT)
        .map(|f| format!("{} {} {}: {}", f.severity, f.category, f.path, f.problem))
        .collect()
}

/// Lower rank sorts first (more severe first).
fn severity_rank(value: &str) -> i32 {
    match value {
        "critical" => 0,
        "high" => 1,
        "error" => 1,
        "medium" => 2,
        "low" => 3,
        _ => 2,
    }
}

/// Tool-adoption opportunities are applicable tools that have not yet reached
/// CI-backed evidence (status `missing` or `configured`).
fn top_tool_opportunities(report: &Report) -> Vec<String> {
    report
        .tool_adoption
        .items
        .iter()
        .filter(|item| item.applicable && matches!(item.status.as_str(), "missing" | "configured"))
        .take(TOP_TOOL_OPPORTUNITIES_LIMIT)
        .map(|item| format!("{} ({})", item.id, item.status))
        .collect()
}

/// Build the matrix with aggregate totals from the projected rows.
fn build_matrix(
    rows: Vec<FleetRow>,
    errors: Vec<FleetError>,
    fail_under: Option<i32>,
) -> FleetMatrix {
    let totals = aggregate_totals(&rows, &errors, fail_under);
    FleetMatrix {
        generated_at_note: GENERATED_AT_NOTE.to_string(),
        repos: rows,
        totals,
        errors,
    }
}

/// Compute min/max/average score, hard-finding totals, and below-threshold count.
fn aggregate_totals(
    rows: &[FleetRow],
    errors: &[FleetError],
    fail_under: Option<i32>,
) -> FleetTotals {
    let audited = rows.len();
    let min_score = rows.iter().map(|r| r.score).min();
    let max_score = rows.iter().map(|r| r.score).max();
    let average_score = if audited == 0 {
        None
    } else {
        let sum: i64 = rows.iter().map(|r| i64::from(r.score)).sum();
        Some(sum as f64 / audited as f64)
    };
    let total_hard_findings = rows.iter().map(|r| r.hard_findings).sum();
    let below_threshold = match fail_under {
        Some(threshold) => rows.iter().filter(|r| r.score < threshold).count(),
        None => 0,
    };
    FleetTotals {
        repo_count: audited + errors.len(),
        audited,
        failed: errors.len(),
        min_score,
        max_score,
        average_score,
        total_hard_findings,
        below_threshold,
    }
}

/// Render the matrix as a sentence-case Markdown table.
fn render_markdown(matrix: &FleetMatrix) -> String {
    use std::fmt::Write;
    let mut out = String::new();
    let _ = writeln!(out, "# jankurai fleet matrix");
    let _ = writeln!(out);
    let _ = writeln!(out, "{}", matrix.generated_at_note);
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "| Name | Path | Score | Raw | Caps | Hard | Conformance level | Host | Branch | Dirty | Version | Fresh | Top findings |"
    );
    let _ = writeln!(
        out,
        "| --- | --- | ---: | ---: | ---: | ---: | --- | --- | --- | ---: | --- | --- | --- |"
    );
    for row in &matrix.repos {
        let findings = if row.top_findings.is_empty() {
            "none".to_string()
        } else {
            row.top_findings
                .iter()
                .map(|f| f.replace('|', "\\|"))
                .collect::<Vec<_>>()
                .join("; ")
        };
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |",
            row.name,
            row.path,
            row.score,
            row.raw,
            row.caps.len(),
            row.hard_findings,
            row.hl_level,
            row.host.as_deref().unwrap_or("—"),
            row.branch.as_deref().unwrap_or("—"),
            row.dirty_files,
            row.version.as_deref().unwrap_or("—"),
            row.score_freshness,
            findings
        );
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "## Totals");
    let _ = writeln!(out);
    let _ = writeln!(out, "- Repos: {}", matrix.totals.repo_count);
    let _ = writeln!(out, "- Audited: {}", matrix.totals.audited);
    let _ = writeln!(out, "- Failed: {}", matrix.totals.failed);
    let _ = writeln!(
        out,
        "- Score range: {} to {}",
        matrix
            .totals
            .min_score
            .map(|s| s.to_string())
            .unwrap_or_else(|| "n/a".into()),
        matrix
            .totals
            .max_score
            .map(|s| s.to_string())
            .unwrap_or_else(|| "n/a".into())
    );
    if let Some(avg) = matrix.totals.average_score {
        let _ = writeln!(out, "- Average score: {avg:.1}");
    }
    let _ = writeln!(
        out,
        "- Hard findings: {}",
        matrix.totals.total_hard_findings
    );
    let _ = writeln!(out, "- Below threshold: {}", matrix.totals.below_threshold);
    if !matrix.errors.is_empty() {
        let _ = writeln!(out);
        let _ = writeln!(out, "## Errors");
        let _ = writeln!(out);
        for err in &matrix.errors {
            let _ = writeln!(out, "- {}: {}", err.path, err.error);
        }
    }
    out
}

/// Write the rendered matrix to the chosen sink (stdout or a file).
fn emit(out: &Option<String>, rendered: &str) -> Result<()> {
    match out {
        Some(path) => crate::render::write_json(path, rendered),
        None => {
            println!("{rendered}");
            Ok(())
        }
    }
}

fn repo_name(repo: &Path) -> String {
    repo.file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .filter(|n| !n.is_empty())
        .unwrap_or_else(|| display_path(repo))
}

fn display_path(repo: &Path) -> String {
    repo.to_string_lossy().into_owned()
}

/// Gather the deterministic repo identity/state fields (git + filesystem + manifest).
/// All cheap, repo-local, network-free — runtime signals (live CI, active runners) are
/// intentionally NOT here; they belong to the JMCP collector, not the quality auditor.
fn repo_metadata(repo: &Path) -> RepoMeta {
    RepoMeta {
        version: repo_version(repo),
        branch: git_branch(repo),
        head_sha: git_str(repo, &["rev-parse", "--short", "HEAD"]),
        dirty_files: dirty_file_count(repo),
        last_commit_epoch: git_commit_epoch(repo),
        last_binary_epoch: newest_mtime(&repo.join("target/release")),
        last_tests_epoch: [
            newest_mtime(&repo.join(".jankurai")),
            newest_mtime(&repo.join("test-results")),
        ]
        .into_iter()
        .flatten()
        .max(),
        host: git_host(repo),
        ci_configured: repo.join(".github/workflows").is_dir(),
    }
}

/// Run a repo-relative git command, returning trimmed stdout on success.
fn git_str(repo: &Path, args: &[&str]) -> Option<String> {
    Command::new("git")
        .args(args)
        .current_dir(repo)
        .output()
        .ok()
        .filter(|out| out.status.success())
        .and_then(|out| String::from_utf8(out.stdout).ok())
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
}

/// Current branch, or `(detached <sha>)` when HEAD is not on a branch.
fn git_branch(repo: &Path) -> Option<String> {
    match git_str(repo, &["rev-parse", "--abbrev-ref", "HEAD"]) {
        Some(branch) if branch != "HEAD" => Some(branch),
        _ => {
            git_str(repo, &["rev-parse", "--short", "HEAD"]).map(|sha| format!("(detached {sha})"))
        }
    }
}

/// Classify the canonical host from origin's URL (forge = local Jeryu, else github/other).
fn git_host(repo: &Path) -> Option<String> {
    let url = git_str(repo, &["remote", "get-url", "origin"])?;
    let host = if url.contains("127.0.0.1:8787") {
        "forge"
    } else if url.contains("github") {
        "github"
    } else {
        "other"
    };
    Some(host.to_string())
}

/// HEAD commit time as raw epoch seconds (deterministic; the dashboard computes age).
fn git_commit_epoch(repo: &Path) -> Option<i64> {
    git_str(repo, &["log", "-1", "--format=%ct"]).and_then(|s| s.parse().ok())
}

/// Count of uncommitted entries (tracked + untracked).
fn dirty_file_count(repo: &Path) -> usize {
    git_str(repo, &["status", "--porcelain"])
        .map(|s| s.lines().filter(|l| !l.is_empty()).count())
        .unwrap_or(0)
}

/// Newest direct-child mtime under `dir` as epoch seconds, or `None` if absent/empty.
fn newest_mtime(dir: &Path) -> Option<i64> {
    if !dir.is_dir() {
        return None;
    }
    let mut newest: Option<i64> = None;
    for entry in std::fs::read_dir(dir).ok()?.flatten() {
        if let Some(secs) = entry
            .metadata()
            .ok()
            .and_then(|m| m.modified().ok())
            .and_then(|t| t.duration_since(UNIX_EPOCH).ok())
            .map(|d| d.as_secs() as i64)
        {
            newest = Some(newest.map_or(secs, |n| n.max(secs)));
        }
    }
    newest
}

/// Per-repo version: workspace.package.version → first member crate's package.version
/// (skipping `version.workspace = true`) → package.json.version → `None`.
fn repo_version(repo: &Path) -> Option<String> {
    if let Ok(text) = std::fs::read_to_string(repo.join("Cargo.toml")) {
        if let Ok(value) = toml::from_str::<toml::Value>(&text) {
            if let Some(v) = value
                .get("workspace")
                .and_then(|w| w.get("package"))
                .and_then(|p| p.get("version"))
                .and_then(|v| v.as_str())
            {
                return Some(v.to_string());
            }
            if let Some(v) = value
                .get("package")
                .and_then(|p| p.get("version"))
                .and_then(|v| v.as_str())
            {
                return Some(v.to_string());
            }
        }
    }
    if let Ok(entries) = std::fs::read_dir(repo.join("crates")) {
        let mut members: Vec<PathBuf> = entries.flatten().map(|e| e.path()).collect();
        members.sort();
        for member in members {
            if let Ok(text) = std::fs::read_to_string(member.join("Cargo.toml")) {
                if let Some(v) = toml::from_str::<toml::Value>(&text)
                    .ok()
                    .as_ref()
                    .and_then(|val| val.get("package"))
                    .and_then(|p| p.get("version"))
                    .and_then(|v| v.as_str())
                {
                    return Some(v.to_string());
                }
            }
        }
    }
    if let Ok(text) = std::fs::read_to_string(repo.join("package.json")) {
        if let Some(v) = serde_json::from_str::<serde_json::Value>(&text)
            .ok()
            .as_ref()
            .and_then(|val| val.get("version"))
            .and_then(|v| v.as_str())
        {
            return Some(v.to_string());
        }
    }
    None
}

/// Persist a repo's audit report to `.jankurai/repo-score.json` so a later `--mode cached`
/// run has inputs. Writes only under the repo's gitignored `.jankurai/`.
fn write_score_cache(repo: &Path, report: &Report) -> Result<()> {
    let dir = repo.join(crate::local_state::LOCAL_ROOT);
    std::fs::create_dir_all(&dir).with_context(|| format!("create {}", dir.display()))?;
    let path = repo.join(crate::local_state::SCORE_JSON);
    let json = serde_json::to_string_pretty(report)?;
    std::fs::write(&path, json).with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn finding(severity: &str, hardness: &str, check_id: &str, problem: &str) -> Finding {
        Finding {
            severity: severity.to_string(),
            category: "test".to_string(),
            path: "src/lib.rs".to_string(),
            problem: problem.to_string(),
            agent_fix: String::new(),
            evidence: vec![],
            check_id: check_id.to_string(),
            hardness: hardness.to_string(),
            confidence: 1.0,
            evidence_kind: "static".to_string(),
            rerun_command: String::new(),
            fingerprint: check_id.to_string(),
            rule_id: None,
            tlr: None,
            lane: None,
            docs_url: None,
            owner: None,
            line: None,
            matched_term: None,
            reason: None,
        }
    }

    fn mock_row(name: &str, score: i32, hard: usize) -> FleetRow {
        FleetRow {
            name: name.to_string(),
            path: format!("/repos/{name}"),
            score,
            raw: score + 2,
            caps: vec!["EXAMPLE-CAP".to_string()],
            hard_findings: hard,
            hl_level: "HL3".to_string(),
            top_findings: vec!["high test src/lib.rs: example".to_string()],
            top_tool_opportunities: vec!["clippy (missing)".to_string()],
            // Fixed, non-time values so golden assertions stay reproducible.
            version: Some("1.0.0".to_string()),
            branch: Some("main".to_string()),
            head_sha: Some("abc1234".to_string()),
            dirty_files: 0,
            last_commit_epoch: None,
            last_binary_epoch: None,
            last_tests_epoch: None,
            host: Some("github".to_string()),
            ci_configured: true,
            score_freshness: "fresh".to_string(),
        }
    }

    fn meta(head: Option<&str>, dirty: usize) -> RepoMeta {
        RepoMeta {
            version: None,
            branch: None,
            head_sha: head.map(String::from),
            dirty_files: dirty,
            last_commit_epoch: None,
            last_binary_epoch: None,
            last_tests_epoch: None,
            host: None,
            ci_configured: false,
        }
    }

    fn cached(head: Option<&str>, auditor: &str) -> CachedScore {
        CachedScore {
            score: 96,
            raw_score: 96,
            caps_applied: vec![],
            observed_conformance_level: "HL3".to_string(),
            auditor_version: auditor.to_string(),
            decision: None,
            git: head.map(|h| CachedGit {
                head: Some(h.to_string()),
            }),
        }
    }

    #[test]
    fn matrix_json_shape_is_stable() {
        let rows = vec![mock_row("alpha", 92, 0), mock_row("beta", 88, 2)];
        let matrix = build_matrix(rows, Vec::new(), Some(85));
        let json = serde_json::to_value(&matrix).unwrap();

        assert_eq!(
            json["generated_at_note"], GENERATED_AT_NOTE,
            "note must be deterministic, not a wall-clock timestamp"
        );
        let repos = json["repos"].as_array().unwrap();
        assert_eq!(repos.len(), 2);
        let first = &repos[0];
        for key in [
            "name",
            "path",
            "score",
            "raw",
            "caps",
            "hard_findings",
            "hl_level",
            "top_findings",
            "top_tool_opportunities",
            // v2 additions (mock_row sets version/branch/host; dirty_files/ci_configured/freshness always present)
            "version",
            "branch",
            "dirty_files",
            "host",
            "ci_configured",
            "score_freshness",
        ] {
            assert!(first.get(key).is_some(), "row missing key {key}");
        }
        // Optional epoch fields are skipped when None; the freshness signal is always one of three states.
        assert!(
            ["fresh", "cached", "stale"].contains(&first["score_freshness"].as_str().unwrap()),
            "score_freshness must be a known state"
        );
        let totals = &json["totals"];
        assert_eq!(totals["repo_count"], 2);
        assert_eq!(totals["audited"], 2);
        assert_eq!(totals["min_score"], 88);
        assert_eq!(totals["max_score"], 92);
        assert_eq!(totals["total_hard_findings"], 2);
        assert_eq!(totals["below_threshold"], 0);
    }

    #[test]
    fn fail_under_counts_repos_below_threshold() {
        let rows = vec![mock_row("alpha", 92, 0), mock_row("beta", 70, 1)];
        let matrix = build_matrix(rows, Vec::new(), Some(85));
        assert_eq!(matrix.totals.below_threshold, 1);
    }

    #[test]
    fn no_fail_under_leaves_below_threshold_zero() {
        let rows = vec![mock_row("alpha", 50, 0)];
        let matrix = build_matrix(rows, Vec::new(), None);
        assert_eq!(matrix.totals.below_threshold, 0);
    }

    #[test]
    fn top_findings_orders_hard_then_severity() {
        let findings = vec![
            finding("low", "soft", "soft-low", "soft low"),
            finding("high", "hard", "hard-high", "hard high"),
            finding("critical", "soft", "soft-critical", "soft critical"),
        ];
        let top = top_findings(&findings);
        assert_eq!(top.len(), 3);
        assert!(top[0].contains("hard high"), "hard finding must sort first");
        assert!(top[1].contains("soft critical"));
        assert!(top[2].contains("soft low"));
    }

    #[test]
    fn top_findings_limited_to_five() {
        let findings: Vec<Finding> = (0..10)
            .map(|i| finding("high", "soft", &format!("check-{i:02}"), "p"))
            .collect();
        let top = top_findings(&findings);
        assert_eq!(top.len(), TOP_FINDINGS_LIMIT);
    }

    #[test]
    fn fleet_config_parses_repos_array() {
        let repos = parse_fleet_config("repos = [\"/a/one\", \"/b/two\"]").unwrap();
        assert_eq!(
            repos,
            vec![PathBuf::from("/a/one"), PathBuf::from("/b/two")]
        );
    }

    #[test]
    fn fleet_config_missing_repos_is_empty() {
        let repos = parse_fleet_config("other = 1").unwrap();
        assert!(repos.is_empty());
    }

    #[test]
    fn markdown_render_uses_sentence_case_headings() {
        let matrix = build_matrix(vec![mock_row("alpha", 92, 0)], Vec::new(), None);
        let md = render_markdown(&matrix);
        assert!(md.contains("# jankurai fleet matrix"));
        assert!(md.contains("| Name | Path | Score |"));
        assert!(md.contains("alpha"));
        // v2 columns render with sentence-case headings.
        assert!(md.contains("| Host | Branch | Dirty | Version | Fresh |"));
        // No screaming all-caps section markers in user-visible output.
        assert!(!md.contains("FLEET MATRIX"));
    }

    #[test]
    fn cached_freshness_is_cached_only_when_head_clean_and_auditor_match() {
        // Matching HEAD + clean worktree + current auditor → safe to reuse.
        assert_eq!(
            cached_freshness(
                &cached(Some("abc1234"), AUDITOR_VERSION),
                &meta(Some("abc1234"), 0)
            ),
            "cached"
        );
        // HEAD moved → stale.
        assert_eq!(
            cached_freshness(
                &cached(Some("abc1234"), AUDITOR_VERSION),
                &meta(Some("def5678"), 0)
            ),
            "stale"
        );
        // Dirty worktree → stale (score predates uncommitted churn).
        assert_eq!(
            cached_freshness(
                &cached(Some("abc1234"), AUDITOR_VERSION),
                &meta(Some("abc1234"), 3)
            ),
            "stale"
        );
        // Auditor bumped → stale (ruleset changed; score not comparable).
        assert_eq!(
            cached_freshness(&cached(Some("abc1234"), "0.0.0"), &meta(Some("abc1234"), 0)),
            "stale"
        );
        // Missing cached HEAD → stale (can't prove currency).
        assert_eq!(
            cached_freshness(&cached(None, AUDITOR_VERSION), &meta(Some("abc1234"), 0)),
            "stale"
        );
    }

    #[test]
    fn newest_mtime_returns_none_for_missing_and_some_for_present() {
        let dir = tempfile::tempdir().unwrap();
        assert_eq!(newest_mtime(&dir.path().join("absent")), None);
        std::fs::write(dir.path().join("a.txt"), "a").unwrap();
        let got = newest_mtime(dir.path());
        assert!(got.is_some() && got.unwrap() > 0);
    }

    #[test]
    fn repo_version_prefers_workspace_then_package_then_none() {
        let none_dir = tempfile::tempdir().unwrap();
        assert_eq!(repo_version(none_dir.path()), None);

        let ws = tempfile::tempdir().unwrap();
        std::fs::write(
            ws.path().join("Cargo.toml"),
            "[workspace.package]\nversion = \"4.2.0\"\n",
        )
        .unwrap();
        assert_eq!(repo_version(ws.path()), Some("4.2.0".to_string()));

        let pkg = tempfile::tempdir().unwrap();
        std::fs::write(
            pkg.path().join("Cargo.toml"),
            "[package]\nname = \"x\"\nversion = \"1.2.3\"\n",
        )
        .unwrap();
        assert_eq!(repo_version(pkg.path()), Some("1.2.3".to_string()));
    }
}
